<?php

namespace AppBundle\Repository;

/**
 * OfficesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficesRepository extends \Doctrine\ORM\EntityRepository
{
}
