<?php

namespace AppBundle\Repository;

/**
 * PhonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhonesRepository extends \Doctrine\ORM\EntityRepository
{
}
