<?php

namespace AppBundle\Repository;

/**
 * SurfacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurfacesRepository extends \Doctrine\ORM\EntityRepository
{
}
