<?php

namespace AppBundle\Repository;

/**
 * WarehousesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehousesRepository extends \Doctrine\ORM\EntityRepository
{
}
